Repository jab0073/CS-499-Statistical-Analyzer, pull requests merged in 2022-10, with the labels that each got.

#9 fixed the validate functions
  src/main/java/Main.java
  src/main/java/Measures/Binomial.java
  src/main/java/Measures/ChiSquare.java
  src/main/java/Measures/CoefficientOfVariance.java
  src/main/java/Measures/CorrelationCoefficient.java
  src/main/java/Measures/LeastSquareLine.java
  src/main/java/Measures/Mean.java
  src/main/java/Measures/Median.java
  src/main/java/Measures/Mode.java
  src/main/java/Measures/Percentiles.java
  src/main/java/Measures/ProbabilityDistribution.java
  src/main/java/Measures/RankSum.java
  src/main/java/Measures/SignTest.java
  src/main/java/Measures/SpearmanRank.java
  src/main/java/Measures/StandardDeviation.java
  src/main/java/Measures/Variance.java
Labels: bug fix

#10 moved file io stuff to dedicated classes
  src/main/java/BackEndUtilities/Constants.java
  src/main/java/BackEndUtilities/DataSet.java
  src/main/java/BackEndUtilities/Sample.java
  src/main/java/Measures/Measures.java
  src/main/java/Measures/UserDefinedMeasure.java
  src/main/java/Respository/FileSystemRepository.java
  src/main/java/Respository/RepositoryManager.java
Labels: enhancement

#15 addressed issues 11-14
  src/main/java/Measures/Binomial.java
  src/main/java/Measures/ChiSquare.java
  src/main/java/Measures/CoefficientOfVariance.java
  src/main/java/Measures/CorrelationCoefficient.java
  src/main/java/Measures/LeastSquareLine.java
  src/main/java/Measures/Mean.java
  src/main/java/Measures/Median.java
  src/main/java/Measures/Mode.java
  src/main/java/Measures/Percentiles.java
  src/main/java/Measures/ProbabilityDistribution.java
  src/main/java/Measures/RankSum.java
  src/main/java/Measures/SignTest.java
  src/main/java/Measures/SpearmanRank.java
  src/main/java/Measures/StandardDeviation.java
  src/main/java/Measures/UserDefinedMeasure.java
  src/main/java/Measures/Variance.java
Labels: enhancement, bug fix

#16 addressed issues 14
  src/main/java/Measures/CorrelationCoefficient.java
  src/main/java/Measures/LeastSquareLine.java
  src/main/java/Measures/SpearmanRank.java
Labels: bug fix

#19 Basic GUI functionality added
  .idea/compiler.xml
  src/main/java/GUI/CellsTable.java
  src/main/java/GUI/Frame.java
  src/main/java/GUI/MenuBar.java
  src/main/java/GUI/MiddlePanel.java
  src/main/java/GUI/RightPanel.java
  src/main/java/Main.java
Labels: enhancement
